import React, { useState } from 'react';
import { ArrowRight, Bluetooth, Cpu, Power, Usb, Wifi } from 'lucide-react';
import { deviceImages, galleryViews } from '../assets/device';
import SectionIntro from '../components/common/SectionIntro';
import DisplayModes from '../components/common/DisplayModes';
import PageCTA from '../components/common/PageCTA';

const specs = [
  ['Product', 'JustRide'], ['Device type', 'Connected motorcycle navigation display'],
  ['Display', '1.8-inch landscape display'], ['Processor', 'ESP32-S3-WROOM-1-N16R8'],
  ['CPU', 'Dual-core Xtensa LX7, up to 240 MHz'], ['Flash', '16 MB'], ['PSRAM', '8 MB'],
  ['Bluetooth', 'Bluetooth 5 Low Energy (BLE)'], ['Wi-Fi', '2.4 GHz 802.11 b/g/n'],
  ['Charging', 'USB-C'], ['PCB size', '53.05 × 79.05 mm'],
  ['PCB thickness', 'Approximately 1.6 mm'], ['Battery physical dimensions', '50 × 34 × 10 mm'],
  ['Navigation source', 'Connected JustRide mobile application'],
];

export default function ProductPage({ navigate }) {
  const [view, setView] = useState(galleryViews[0]);
  return <>
    <section className="product-hero"><div className="container product-hero__grid"><div><p className="eyebrow eyebrow--line">THE JUSTRIDE DEVICE</p><h1>Meet <em>JustRide.</em></h1><p className="hero-lede">A compact connected navigation display designed around the motorcycle riding experience.</p><p className="product-hero__micro"><span className="proof-dot" /> Connected through Bluetooth Low Energy.</p><a className="button button--primary" href="#gallery">Explore the device <ArrowRight size={17} /></a></div><div className="product-hero__image"><img src={deviceImages.perspective} alt="Perspective render of the JustRide navigation device" width="1254" height="1254" fetchPriority="high" /></div></div></section>

    <section className="section section--light" id="gallery"><div className="container"><SectionIntro eyebrow="PRODUCT GALLERY" title="Explore the device from four sides.">Choose a front, back, left, or right view of JustRide.</SectionIntro><div className="gallery-layout"><div className="gallery-stage">{galleryViews.map((item) => <div key={item.id} className={`gallery-stage__layer ${view.id === item.id ? 'is-visible' : ''}`} aria-hidden={view.id !== item.id}><img src={deviceImages[item.id]} alt={item.alt} width="1254" height="1254" loading="lazy" /></div>)}<span>{view.label.toUpperCase()} VIEW</span></div><div className="gallery-tabs" role="group" aria-label="Choose device view">{galleryViews.map((item) => <button type="button" key={item.id} className={view.id === item.id ? 'is-active' : ''} aria-pressed={view.id === item.id} onClick={() => setView(item)}><img src={deviceImages[item.id]} alt="" width="1254" height="1254" loading="lazy" /><span>{item.label}</span></button>)}</div></div></div></section>

    <section className="section"><div className="container editorial-grid"><div className="editorial-image editorial-image--dark"><img src={deviceImages.front} alt="Front of the JustRide 1.8-inch landscape display with navigation information" width="1254" height="1254" loading="lazy" /><span className="image-index">01 / DISPLAY</span></div><div className="editorial-copy"><SectionIntro eyebrow="THE DISPLAY" title="1.8-inch landscape display">A compact landscape layout designed around clear navigation hierarchy.</SectionIntro><div className="tag-list"><span>Next maneuver</span><span>Distance</span><span>Route map</span><span>Speed</span><span>ETA</span><span>Battery</span><span>Connection</span></div><p className="muted-note">Speed limit information appears where available; current speed appears where implemented.</p></div></div></section>

    <section className="section section--subtle"><div className="container editorial-grid"><div className="editorial-copy"><SectionIntro eyebrow="PROCESSING + CONNECTIVITY" title="Powered by ESP32-S3">The ESP32-S3-WROOM-1-N16R8 supports the dedicated display and its connected experience.</SectionIntro><div className="inline-facts"><div><Cpu size={22} /><strong>Dual-core Xtensa LX7</strong><span>Up to 240 MHz</span></div><div><strong>16 MB</strong><span>Flash</span></div><div><strong>8 MB</strong><span>PSRAM</span></div></div><p className="section-lede">Bluetooth 5 Low Energy (BLE) connects the device with the JustRide mobile app. The module also supports 2.4 GHz Wi-Fi.</p></div><div className="hardware-panel"><div className="hardware-panel__top"><span>CONNECTED HARDWARE</span><Cpu size={26} /></div><div className="hardware-panel__center">ESP32<span>—S3</span></div><div className="hardware-panel__bottom"><span><Bluetooth size={17} /> Bluetooth 5 LE</span><span><Wifi size={17} /> 2.4 GHz Wi-Fi</span></div></div></div></section>

    <section className="section"><div className="container editorial-grid"><div className="editorial-image editorial-image--dark"><img src={deviceImages.right} alt="JustRide side profile showing its enclosure and side port" width="1254" height="1254" loading="lazy" /><span className="image-index">02 / ENCLOSURE</span></div><div className="editorial-copy"><SectionIntro eyebrow="PHYSICAL DETAILS" title="The controls you need.">A physical front power button provides a clear tactile control. USB-C handles charging.</SectionIntro><div className="detail-stack"><div><Power size={22} /><div><strong>Dedicated front power control</strong><p>Black button with an emerald power icon.</p></div></div><div><Usb size={22} /><div><strong>USB-C charging</strong><p>A familiar connection on the side of the device.</p></div></div></div></div></div></section>

    <section className="section section--light"><div className="container editorial-grid"><div className="editorial-copy"><SectionIntro eyebrow="NAVIGATION EXPERIENCE" title="Built around the next move.">The phone handles navigation and route processing. JustRide shows the current maneuver, distance and route in a dedicated rider display.</SectionIntro><ul className="feature-list"><li><strong>At a glance</strong><span>Large turn and distance information.</span></li><li><strong>Route context</strong><span>A focused map and relevant trip information.</span></li><li><strong>When routes change</strong><span>Updated information can be sent to the device through the connected system.</span></li></ul></div><div className="editorial-image editorial-image--light"><img src={deviceImages.mounted} alt="JustRide mounted on a motorcycle with navigation visible" width="1448" height="1086" loading="lazy" /><span className="image-index">03 / ON THE BIKE</span></div></div></section>

    <DisplayModes />

    <section className="section specs-section"><div className="container specs-layout"><div><SectionIntro eyebrow="TECHNICAL SPECIFICATIONS" title="The details, clearly stated.">Confirmed hardware information for the JustRide device.</SectionIntro><p className="muted-note">PCB and battery measurements refer to internal parts, not the overall enclosure. Overall device dimensions are not yet confirmed.</p></div><div className="spec-table" role="table" aria-label="JustRide specifications">{specs.map(([label, value]) => <div className="spec-row" role="row" key={label}><span role="cell">{label}</span><strong role="cell">{value}</strong></div>)}</div></div></section>

    <section className="section section--subtle"><div className="container app-integration"><div><SectionIntro eyebrow="APP + DEVICE" title="One connected riding experience.">The mobile app prepares and processes the route. Backend services and firmware support the system. Bluetooth Low Energy brings the essential instructions to the hardware display.</SectionIntro><a className="text-link" href="/download" onClick={(event) => navigate(event, 'download')}>Explore the app <ArrowRight size={17} /></a></div><div className="connection-card"><div><span>01</span><strong>JustRide app</strong><small>Destination + route</small></div><div><span>02</span><strong>Bluetooth LE</strong><small>Essential information</small></div><div><span>03</span><strong>JustRide device</strong><small>Rider display</small></div></div></div></section>

    <section className="section faq-section"><div className="container"><SectionIntro eyebrow="PRODUCT NOTES" title="Good to know." /><div className="faq-list"><details><summary>Does JustRide replace my phone?</summary><p>No. The mobile app handles navigation and route processing, while the device presents the essentials on a dedicated display.</p></details><details><summary>Does the display support day and night modes?</summary><p>Yes. Use the Day/Night control above to compare the supplied interface images.</p></details><details><summary>What happens if I miss a turn?</summary><p>When the navigation system detects a route deviation, updated route information can be synchronized back to the device.</p></details></div></div></section>
    <PageCTA navigate={navigate} />
  </>;
}
